name: IA Code Review on PR

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  ai_review:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: pip install openai

    - name: Run AI reviewer
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        git log -n 10 --pretty=format:"%h %s" > commits.txt
        python review_commits.py

    - name: Comment PR with AI review
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        path: revision.txt
