name: IA Code Review on PR

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  ai_review:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: pip install openai

    - name: Obtener commits del PR
      run: git log -n 10 --pretty=format:"%h %s" > commits.txt

    - name: Mostrar commits.txt para debug
      run: cat commits.txt

    - name: Ejecutar revisión AI
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: python review_commits.py

    - name: Mostrar revision.txt para debug
      run: cat revision.txt

    - name: Comentar revisión en PR
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        path: revision.txt
